- name: Install the NTP daemon to synchronize the clocks to ms.
  package: 
    name: ntp
    state: present

- name: Make sure ntp is started, and is enabled on restart.
  service: name=ntp state=started enabled=yes

